version: "3.8"
services:
  api:
    platform: linux/amd64
    build: ./backend
    ports:
      - 5001:5001
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__db=Server=db;Database=splashdb;User Id=postgres;
      - Urls=http://+:5001
    depends_on:
      - db
    volumes:
      - ./backend/web/appsettings.Development.json:/app/appsettings.Development.json
    entrypoint:
    - dotnet
    - web.dll

  db:
    image: postgres:14.4
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 5432:5432

volumes:
  postgres_data:
